String googleApis = 'www.googleapis.com';
String imageHdQuality = '/hqdefault.jpg';
String imageMaxQuality = '/maxresdefault.jpg';
String supportUs = 'https://ko-fi.com/nerdvalorant';
String thumbnailInitialUrl = 'https://i.ytimg.com/vi/nv-id';
String instagram = 'https://www.instagram.com/nerdvalorantoficial';
String baseLink = 'https://sites.google.com/nerdvalorant.com.br/security';
String playStoreDetails = 'https://play.google.com/store/apps/details?id=';
String hateMyAppOnPlayStore = '${playStoreDetails}br.com.codemos.nerdvalorant';
